# Generated by Django 5.2.11 on 2026-02-14 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("codigo", models.CharField(blank=True, max_length=50, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "Tienda",
                "verbose_name_plural": "Tiendas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Rack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_qr",
                    models.CharField(
                        db_index=True,
                        help_text="ID único en el código QR del rack",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Bodega norte, Pasillo 3",
                        max_length=200,
                    ),
                ),
                (
                    "compresores_media",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Cantidad compresores media"
                    ),
                ),
                (
                    "compresores_baja",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Cantidad compresores baja"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="racks",
                        to="inventory.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rack",
                "verbose_name_plural": "Racks",
                "ordering": ["tienda", "id_qr"],
            },
        ),
    ]
