# Generated by Django 5.2.11 on 2026-02-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rack",
            name="Refigerante",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
