# Generated by Django 5.2.11 on 2026-02-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rack_refigerante"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rack",
            old_name="Refigerante",
            new_name="refigerante",
        ),
    ]
