# Generated by Django 5.2.11 on 2026-05-04 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_compresor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_qr', models.CharField(db_index=True, help_text='ID único en el código QR de la planta', max_length=100, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('capacidad_kva', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacidad (KVA)')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Patio trasero, Cuarto de máquinas', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantas_electricas', to='inventory.tienda')),
            ],
            options={
                'verbose_name': 'Planta Eléctrica',
                'verbose_name_plural': 'Plantas Eléctricas',
                'ordering': ['tienda', 'id_qr'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('bateria_cantidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de baterías')),
                ('bateria_modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo de batería')),
                ('bateria_fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha instalación batería')),
                ('bateria_estado_cargador', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Estado cargador')),
                ('bateria_nivel_carga', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Nivel de carga')),
                ('fugas_aceite_combustible', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Fugas aceite/combustible')),
                ('nivel_combustible', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Nivel combustible')),
                ('tipo_radiador', models.CharField(blank=True, max_length=100, verbose_name='Tipo de radiador')),
                ('nivel_agua_radiador', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Nivel agua radiador')),
                ('nivel_aceite', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Nivel de aceite')),
                ('horas_funcionamiento', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Horas de funcionamiento')),
                ('obstruccion', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Obstrucción')),
                ('voltaje_l1l2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje L1-L2')),
                ('voltaje_l2l3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje L2-L3')),
                ('voltaje_l1l3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje L1-L3')),
                ('voltaje_l1n', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje L1-N')),
                ('voltaje_l2n', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje L2-N')),
                ('voltaje_l3n', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje L3-N')),
                ('amperaje_a1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Amperaje A1')),
                ('amperaje_a2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Amperaje A2')),
                ('amperaje_a3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Amperaje A3')),
                ('voltaje_generador', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje generador')),
                ('frecuencia_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frecuencia (Hz)')),
                ('rpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='RPM')),
                ('voltaje_dc_cargador', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voltaje DC cargador')),
                ('arranque_vacio', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Arranque en vacío')),
                ('prueba_transferencia_carga', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=20, verbose_name='Prueba transferencia con carga')),
                ('observaciones', models.TextField(blank=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='inventory.plantaelectrica')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_planta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Revisión Planta',
                'verbose_name_plural': 'Registros de Revisión Plantas',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
