# Generated by Django 5.2.11 on 2026-09-05 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_plantaelectrica_registroplanta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Zona",
                "verbose_name_plural": "Zonas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="tienda",
            name="zona",
            field=models.ForeignKey(
                blank=True,
                help_text="Zona a la que pertenece este punto de venta",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tiendas",
                to="inventory.zona",
            ),
        ),
        migrations.CreateModel(
            name="AsignacionTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(
                        choices=[("racks", "Racks"), ("plantas", "Plantas Eléctricas")],
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_preventivo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_preventivo",
                        to="inventory.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de preventivo",
                "verbose_name_plural": "Asignaciones de preventivos",
                "ordering": ["especialidad", "tienda__nombre"],
                "unique_together": {("tecnico", "tienda", "especialidad")},
            },
        ),
    ]
