# Generated by Django 5.2.11 on 2026-02-14 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_rename_refigerante_rack_refigerante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[
                            ("preventivo", "Mantenimiento Preventivo"),
                            ("correctivo", "Mantenimiento Correctivo"),
                            ("emergencia", "Emergencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hora_inicio", models.DateTimeField()),
                ("hora_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "datos_entrada",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Presiones, temperaturas, setpoints, amperajes al inicio",
                    ),
                ),
                (
                    "datos_salida",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parámetros finales para comparar",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("cerrado", models.BooleanField(default=False)),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="inventory.rack",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_actividad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de actividad",
                "verbose_name_plural": "Registros de actividad",
                "ordering": ["-hora_inicio"],
            },
        ),
    ]
